FROM node:latest AS buildUi
ENV DOCKER_BUILDKIT=1
WORKDIR /src
COPY ["/src/DevRel.Web.Host/clientApp/", "clientApp/"]
WORKDIR /src/clientApp
RUN npm i --force && npm run ng build

FROM scratch AS export-stage
COPY --from=buildUi /src/wwwroot /
