name: Build artifact

on:
  workflow_dispatch:
  push:
    branches:
      - master

jobs:
  build_back:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout project
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v3

      - name: Build image
        run: docker buildx build -o back . -f src/DevRel.Web.Host/Dockerfile.BuildBack

      - uses: actions/upload-artifact@v3
        with:
          name: backend
          path: back

  build_ui:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout project
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v3

      - name: Build image
        run: docker buildx build -o ui . -f src/DevRel.Web.Host/Dockerfile.BuildUi

      - uses: actions/upload-artifact@v3
        with:
          name: ui
          path: ui

  deploy:
    runs-on: ubuntu-latest
    needs: [build_back, build_ui]
    steps:
      - uses: actions/download-artifact@v3
        with:
          name: ui

      - uses: actions/download-artifact@v3
        with:
          name: backend

      - name: Combine artifacts
        run: ls && unzip backend.zip -d back && unzip ui.zip && ls && mv dist back/wwwroot && ls

      - uses: actions/upload-artifact@v3
        with:
          name: all-artifacts
          path: back
