name: Build artifact

on:
  workflow_dispatch:
  push:
    branches:
      - master

jobs:
  build_and_upload:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout project
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v3

      - name: Build image
        run: docker buildx build -o back . -f src/DevRel.Web.Host/Dockerfile.BuildBack

      - uses: actions/upload-artifact@v3
        with:
          name: backend
          path: back

      # - name: Build image
      #   run: docker build . -t backend:latest -f src/DevRel.Web.Host/Dockerfile.BuildBack

      # - name: Publish backend
      #   uses: ishworkh/container-image-artifact-upload@v1.0.0
      #   with:
      #     image: "backend:latest"
