name: Build artifact

on:
  workflow_dispatch
  push:
    branches:
      - master

jobs:
  build_and_upload:
    - name: Checkout project
      uses: actions/checkout@v2
      
    - name: Build image
      run: docker build -t . -f src/DevRel.Web.Host/Dockerfile.BuildBack backend:latest 

    - name: Publish backend
      uses: ishworkh/container-image-artifact-upload@v1.0.0
      with:
        image: "backend:latest"